version: '2'
services:

  wordpress:
    image: wordpress:4.7.3-apache
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    links:
      - database
    environment:
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_HOST: database:3306

  database:
    image: mariadb:10.1.22
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wp
